<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Propel\Tests\Generator\Platform;

use Propel\Generator\Model\CheckConstraint;
use Propel\Generator\Model\Column;
use Propel\Generator\Model\Database;
use Propel\Generator\Model\IdMethod;
use Propel\Generator\Model\PropelTypes;
use Propel\Generator\Model\Table;
use Propel\Generator\Platform\PgsqlPlatform;
use Propel\Generator\Platform\PlatformInterface;

/**
 * Phase C (umbrella §6.4) — PostgreSQL emits JSONB / generated / IDENTITY / CHECK DDL.
 */
class PgsqlPlatformPhaseCTest extends PlatformTestBase
{
    /**
     * @return \Propel\Generator\Platform\PgsqlPlatform
     */
    protected function getPlatform(): PlatformInterface
    {
        return new PgsqlPlatform();
    }

    /**
     * @return void
     */
    public function testSupportsFlags(): void
    {
        $p = $this->getPlatform();
        $this->assertTrue($p->supportsGeneratedColumns());
        $this->assertFalse($p->supportsInvisibleColumns(), 'PG has no INVISIBLE');
        $this->assertTrue($p->supportsCheckConstraints());
    }

    /**
     * @return void
     */
    public function testStoredGeneratedColumnDDL(): void
    {
        $platform = $this->getPlatform();
        $database = new Database();
        $database->setPlatform($platform);
        $table = new Table('users');
        $database->addTable($table);

        $col = new Column('full_name');
        $col->setDomain($platform->getDomainForType(PropelTypes::VARCHAR));
        $col->setSize(200);
        $table->addColumn($col);
        $col->setGenerated('stored', "first_name || ' ' || last_name");

        $ddl = $platform->getColumnDDL($col);
        $this->assertStringContainsString("GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED", $ddl);
    }

    /**
     * @return void
     */
    public function testVirtualFoldsToStoredOnPg(): void
    {
        $platform = $this->getPlatform();
        $database = new Database();
        $database->setPlatform($platform);
        $table = new Table('users');
        $database->addTable($table);

        $col = new Column('total');
        $col->setDomain($platform->getDomainForType(PropelTypes::INTEGER));
        $table->addColumn($col);
        $col->setGenerated('virtual', 'a + b');

        $ddl = $platform->getColumnDDL($col);
        // PG has no VIRTUAL — falls back to STORED.
        $this->assertStringContainsString('GENERATED ALWAYS AS (a + b) STORED', $ddl);
    }

    /**
     * @return void
     */
    public function testIdentityForAutoIncrementByDefault(): void
    {
        $platform = $this->getPlatform();
        $database = new Database();
        $database->setPlatform($platform);
        $table = new Table('users');
        $table->setIdMethod(IdMethod::NATIVE);
        $database->addTable($table);

        $col = new Column('id');
        $col->setDomain($platform->getDomainForType(PropelTypes::INTEGER));
        $col->setPrimaryKey(true);
        $col->setAutoIncrement(true);
        $table->addColumn($col);

        $ddl = $platform->getColumnDDL($col);
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $ddl);
        $this->assertStringNotContainsString('serial', $ddl);
    }

    /**
     * @return void
     */
    public function testLegacySerialFlagIsHardErrorInPropel4(): void
    {
        // Phase G.2.6 (Propel 4.0): the `legacy-serial` PG vendor flag was
        // deprecated in 3.0 with a 1-minor runway and now throws. Schemas
        // must migrate to <column type="IDENTITY"> for SQL:2003 IDENTITY
        // columns.
        $platform = $this->getPlatform();
        $database = new Database();
        $database->setPlatform($platform);
        $table = new Table('users');
        $table->setIdMethod(IdMethod::NATIVE);
        $database->addTable($table);

        $col = new Column('id');
        $col->setDomain($platform->getDomainForType(PropelTypes::INTEGER));
        $col->setPrimaryKey(true);
        $col->setAutoIncrement(true);
        $vendor = new \Propel\Generator\Model\VendorInfo('pgsql');
        $vendor->setParameter('legacy-serial', 'true');
        $col->addVendorInfo($vendor);
        $table->addColumn($col);

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('legacy-serial');

        $platform->getColumnDDL($col);
    }

    /**
     * @return void
     */
    public function testCheckConstraintEnforced(): void
    {
        $platform = $this->getPlatform();
        $cc = new CheckConstraint('ck_orders_qty', 'quantity > 0');
        $ddl = $platform->getCheckConstraintDDL($cc);
        $this->assertStringContainsString('CONSTRAINT', $ddl);
        $this->assertStringContainsString('"ck_orders_qty"', $ddl);
        $this->assertStringContainsString('CHECK (quantity > 0)', $ddl);
        $this->assertStringNotContainsString('NOT VALID', $ddl);
    }

    /**
     * @return void
     */
    public function testCheckConstraintNotValid(): void
    {
        $platform = $this->getPlatform();
        $cc = new CheckConstraint('ck_orders_qty', 'quantity > 0', false);
        $ddl = $platform->getCheckConstraintDDL($cc);
        $this->assertStringContainsString('NOT VALID', $ddl);
    }

    /**
     * @return void
     */
    public function testJsonbColumnTypeRendersAsJsonb(): void
    {
        $platform = $this->getPlatform();
        $database = new Database();
        $database->setPlatform($platform);
        $table = new Table('events');
        $database->addTable($table);

        $col = new Column('payload');
        $col->setDomain($platform->getDomainForType(PropelTypes::JSONB));
        $table->addColumn($col);

        $ddl = $platform->getColumnDDL($col);
        $this->assertStringContainsString('JSONB', $ddl);
    }

    /**
     * @return void
     */
    public function testCreateTableInlineCheckConstraints(): void
    {
        $xml = <<<'XML'
<database name="phase_c">
    <table name="orders">
        <column name="id" type="INTEGER" primaryKey="true" autoIncrement="true"/>
        <column name="discount_pct" type="DECIMAL" size="5" scale="2"/>
        <check name="ck_orders_discount_range" expression="discount_pct BETWEEN 0 AND 100"/>
    </table>
</database>
XML;
        $table = $this->getTableFromSchema($xml, 'orders');
        $sql = $this->getPlatform()->getAddTableDDL($table);

        $this->assertStringContainsString('CONSTRAINT "ck_orders_discount_range" CHECK (discount_pct BETWEEN 0 AND 100)', $sql);
    }
}
