<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Propel\Generator\Model;

/**
 * Enum for ID method types used in Propel models.
 *
 * @author Hans Lellelid <hans@xmpl.org> (Propel)
 * @author Daniel Rall <dlr@collab.net> (Torque)
 */
enum IdMethodType: string
{
    /**
     * Key generation via database-specific ID method
     * (i.e. auto-increment for MySQL, sequence for Oracle, etc.).
     */
    case NATIVE = 'native';

    /**
     * No RDBMS key generation (keys may be generated by the
     * application).
     */
    case NO_ID_METHOD = 'none';
}
